package jdbcexamples;

public class JDBCTest {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		EmployeeDAO employeeDAO = new EmployeeDAOImpl();
		
		
		//Employee employee = new Employee(empId, firstName, lastName, salary); 
		
		Employee employee = new Employee(0, "Rajesh Reddy", "VEnkata Laxmana", 10000);
		System.out.println(employeeDAO.insertEmployeePreParedAutoGenerated(employee));
		
		System.out.println(employeeDAO.getEmployees());
		
		

	}

}
